name: Semifold CI
on:
  push:
    branches: [main]

env:
  CLICOLOR_FORCE: 1

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: Version or Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Semifold
        uses: noctisynth/setup-semifold@main
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup cargo-aur
        run: cargo install cargo-aur
      - name: Install Makepkg
        run: sudo apt-get update && sudo apt-get install -y makepkg pacman
      - name: Run cargo-aur
        run: cargo aur
      - name: Semifold CI
        run: semifold ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
